project:
  type: website

website:
  title: "bob"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jakeybob
      - icon: twitter
        href: https://twitter.com/jakeybob
format:
  html:
    theme: cosmo
    css: styles.css



