project:
  type: website
execute:
  freeze: auto
website:
  title: "bobt.me"
  site-url: "https://bobt.me"
  navbar:
    right:
      - posts.qmd
      - icon: github
        href: https://github.com/jakeybob
      - icon: twitter
        href: https://twitter.com/jakeybob
      - icon: mastodon
        href: https://mastodon.scot/@jakeybob
  twitter-card:
    creator: "@jakeybob"
  open-graph:
    locale: en_GB
    site-name: bobt.me
format:
  html:
    theme: cerulean
    css: styles.css

