project:
  type: website
execute:
  freeze: auto
website:
  title: "bobt.me"
  navbar:
    right:
      - posts.qmd
      - icon: github
        href: https://github.com/jakeybob
      - icon: twitter
        href: https://twitter.com/jakeybob
      - icon: mastodon
        href: https://mastodon.scot/@jakeybob
format:
  html:
    theme: cosmo
    css: styles.css



