project:
  type: website
  render:
    - "*.qmd"
    - "!draft*.qmd"
    - "!ignore*.qmd"
execute:
  freeze: auto
website:
  title: "bobt.me"
  site-url: "https://bobt.me"
  favicon: favicon.png
  navbar:
    # background: dark
    background: primary
    right:
      - posts.qmd
      - icon: github
        href: https://github.com/jakeybob
        aria-label: Bob Taylor's GitHub
      - icon: mastodon
        href: https://mastodon.scot/@jakeybob
        aria-label: Bob Taylor's Mastodon
      - icon: twitter
        href: https://twitter.com/jakeybob
        aria-label: Bob Taylor's Twitter
  twitter-card:
    creator: "@jakeybob"
  open-graph:
    locale: en_GB
    site-name: bobt.me
format:
  html:
    theme: pulse
    css: styles.css

